package main

import "fmt"

func main() {
	fmt.Println("Khet")
	fmt.Println("Com")
	fmt.Println("Bam")
	fmt.Println("Boat")
	fmt.Println("Ice")
	fmt.Println("Fang")
	fmt.Println("Tan")
	fmt.Println("Nan")
	fmt.Println("Arm")
	fmt.Println("Pie")
	fmt.Println("Egg")
	fmt.Println("Mook")
	fmt.Println("Kao")
	fmt.Println("Mind")
	fmt.Println("Ter")
	fmt.Println("Bee")
	fmt.Println("Sun")
	fmt.Println("Nueng")
	fmt.Println("May")
	fmt.Println("Aum")
	fmt.Println("Mark")
	fmt.Println("Cartoon")
	fmt.Println("Bas")
	fmt.Println("Jah")
	fmt.Println("Fluk")
	fmt.Println("Meena")